sudo: required
env:
  - DOCKER_TAG=debian_testing
  - DOCKER_TAG=debian_stable
  - DOCKER_TAG=ubuntu_eoan
  - DOCKER_TAG=ubuntu_focal
services:
- docker
script:
- export TRAVIS_COMMIT_SHORT="$(git rev-parse --short ${TRAVIS_COMMIT})"
- docker build . --tag liquidsoap-build --no-cache --build-arg DOCKER_TAG --build-arg TRAVIS_BRANCH --build-arg TRAVIS_COMMIT --build-arg TRAVIS_COMMIT_SHORT --build-arg TRAVIS_PULL_REQUEST --build-arg TRAVIS_PULL_REQUEST_BRANCH --build-arg TRAVIS_BUILD_NUMBER -f .ci/travis/Dockerfile
- ./.ci/travis/get-deb.sh

deploy:
  provider: s3
  access_key_id: AKIA6KFHFXRI5AQ2J4KY
  secret_access_key:
    secure: J0Alq2DgQ4q3Hy82Mkn1CfjSIMCkXdhdfDovQOWCNlSox8JzQWM/OF8+ePZQSeZ3tL/nrEEtu0vGlgPp22/EE4BJyXKPd8vnWgNE8xq7dpYSPnt9rDDqcIOtM/xXAmIpfTFs6Gc0KY+EPIPPZV3ySAvLyTFIhN0SgX/kkgYshr0=
  bucket: deb.liquidsoap.info
  skip_cleanup: true
  local_dir: debian
  acl: public_read
  on:
    repo: savonet/liquidsoap
    all_branches: true
