name: Backport

on:
  pull_request_target:
    types: [closed, labeled]

jobs:
  notify:
    if: github.event.action == 'labeled' && startsWith(github.event.label.name, 'backport ')
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            const label = context.payload.label.name;
            const branch = label.replace('backport ', '');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Scheduled for backport to \`${branch}\` when this PR is merged.`
            });

  backport:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true && contains(toJSON(github.event.pull_request.labels.*.name), 'backport:')
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/backport@9565281eda0731b1d20c4025c43339fb0a23812e # v2.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
